### PR TITLE
Fix: Allow 'CMD ...' to match any CMD instructions

### PR DESCRIPTION
**Pull request by ajbt200128**
Part of fix for  returntocorp/semgrep#4770

### CODE REVIEW

**Comment by ajbt200128** [comment]
Note: will need someone to publish this for me

**Comment by aryx** [comment]
@ajbt200128 you probably want to do the PR on the original tree-sitter-dockerfile, not on this fork. https://github.com/camdencheek/tree-sitter-dockerfile
cc @mjambon

**Comment by aryx** [comment]
Then what you need is to make a PR on https://github.com/returntocorp/ocaml-tree-sitter-semgrep that use a new tree-sitter-dockerfile. From there we can publish a new semgrep-dockerfile that can be used inside semgrep.
I know it's a bit complicated. There's some documentation here: https://github.com/returntocorp/ocaml-tree-sitter-semgrep/tree/main/doc

**Comment by mjambon** [comment]
A deduplication is nice but it's not really needed. I try to avoid touching too many repos at once unless it's necessary. In https://github.com/returntocorp/ocaml-tree-sitter-semgrep/pull/293, I extend the `shell_command` rule which should work.

**Pull request closed without merging**
